export const MOCK_STOCKS = [
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    price: 173.5,
    change: 1.25,
    changePercent: 0.72,
    volume: "52M",
    marketCap: "2.7T",
    peRatio: 28.5,
    sector: "Technology",
    high52: 198.23,
    low52: 160.1,
    description:
      "Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide.",
  },
  {
    symbol: "MSFT",
    name: "Microsoft Corp",
    price: 330.1,
    change: -2.1,
    changePercent: -0.63,
    volume: "22M",
    marketCap: "2.5T",
    peRatio: 32.1,
    sector: "Technology",
    high52: 366.78,
    low52: 270.0,
    description:
      "Microsoft Corporation develops, licenses, and supports software, services, devices, and solutions worldwide.",
  },
  {
    symbol: "GOOGL",
    name: "Alphabet Inc.",
    price: 138.9,
    change: 0.8,
    changePercent: 0.58,
    volume: "18M",
    marketCap: "1.7T",
    peRatio: 24.8,
    sector: "Communication",
    high52: 151.0,
    low52: 115.0,
    description:
      "Alphabet Inc. offers various products and platforms in the United States, Europe, the Middle East, Africa, the Asia-Pacific, Canada, and Latin America.",
  },
  {
    symbol: "AMZN",
    name: "Amazon.com Inc.",
    price: 129.3,
    change: 3.4,
    changePercent: 2.7,
    volume: "45M",
    marketCap: "1.3T",
    peRatio: 60.2,
    sector: "Consumer Cyclical",
    high52: 145.86,
    low52: 101.15,
    description:
      "Amazon.com, Inc. engages in the retail sale of consumer products and subscriptions in North America and internationally.",
  },
  {
    symbol: "TSLA",
    name: "Tesla Inc.",
    price: 240.5,
    change: -5.2,
    changePercent: -2.12,
    volume: "98M",
    marketCap: "760B",
    peRatio: 70.5,
    sector: "Consumer Cyclical",
    high52: 299.29,
    low52: 152.37,
    description:
      "Tesla, Inc. designs, develops, manufactures, leases, and sells electric vehicles, and energy generation and storage systems in the United States, China, and internationally.",
  },
  {
    symbol: "JPM",
    name: "JPMorgan Chase",
    price: 148.2,
    change: 0.5,
    changePercent: 0.34,
    volume: "9M",
    marketCap: "430B",
    peRatio: 10.2,
    sector: "Financial",
    high52: 159.38,
    low52: 123.11,
    description:
      "JPMorgan Chase & Co. operates as a financial services company worldwide.",
  },
  {
    symbol: "JNJ",
    name: "Johnson & Johnson",
    price: 155.0,
    change: -0.2,
    changePercent: -0.13,
    volume: "6M",
    marketCap: "400B",
    peRatio: 15.6,
    sector: "Healthcare",
    high52: 175.97,
    low52: 144.95,
    description:
      "Johnson & Johnson develops medical devices, pharmaceuticals, and consumer packaged goods.",
  },
  {
    symbol: "NVDA",
    name: "NVIDIA Corp",
    price: 460.15,
    change: 10.5,
    changePercent: 2.34,
    volume: "40M",
    marketCap: "1.1T",
    peRatio: 110.5,
    sector: "Technology",
    high52: 502.66,
    low52: 250.0,
    description:
      "NVIDIA Corporation provides graphics, compute and networking solutions in the United States, Taiwan, China, and internationally.",
  },
  {
    symbol: "PG",
    name: "Procter & Gamble",
    price: 152.4,
    change: 0.1,
    changePercent: 0.07,
    volume: "5M",
    marketCap: "360B",
    peRatio: 24.5,
    sector: "Consumer Defensive",
    high52: 158.38,
    low52: 135.0,
    description:
      "The Procter & Gamble Company provides branded consumer packaged goods to consumers in North and Latin America, Europe, the Asia Pacific, Greater China, India, the Middle East, and Africa.",
  },
  {
    symbol: "XOM",
    name: "Exxon Mobil",
    price: 115.8,
    change: 1.8,
    changePercent: 1.58,
    volume: "14M",
    marketCap: "460B",
    peRatio: 9.8,
    sector: "Energy",
    high52: 120.7,
    low52: 98.0,
    description:
      "Exxon Mobil Corporation explores for and produces crude oil and natural gas in the United States and internationally.",
  },
];
