import React from "react";
import { GraduationCap, BookOpen } from "lucide-react";

const ContentViewer = ({ selectedTopic, content, loading }) => {
  return (
    <div className="bg-white rounded-xl shadow-sm border border-slate-100 overflow-hidden flex flex-col">
      {selectedTopic ? (
        <div className="flex-1 p-8 overflow-y-auto">
          <div className="flex items-center gap-3 mb-6">
            <div className="p-2 bg-indigo-100 rounded-lg text-indigo-600">
              <GraduationCap size={24} />
            </div>
            <h2 className="text-2xl font-bold text-slate-900">
              {selectedTopic}
            </h2>
          </div>

          {loading ? (
            <div className="space-y-4 animate-pulse">
              <div className="h-4 bg-slate-200 rounded w-3/4" />
              <div className="h-4 bg-slate-200 rounded w-full" />
              <div className="h-4 bg-slate-200 rounded w-5/6" />
              <div className="h-4 bg-slate-200 rounded w-full" />
            </div>
          ) : (
            <div className="prose prose-slate max-w-none">
              <div className="markdown-content text-slate-700 leading-7">
                {content.split("\n").map((line, i) => {
                  if (line.startsWith("##"))
                    return (
                      <h3
                        key={i}
                        className="text-lg font-bold mt-6 mb-2 text-slate-900"
                      >
                        {line.replace("##", "")}
                      </h3>
                    );
                  if (line.startsWith("*") || line.startsWith("-"))
                    return (
                      <li key={i} className="ml-4 text-slate-600">
                        {line.replace(/[*|-]/, "")}
                      </li>
                    );
                  return (
                    <p key={i} className="mb-4">
                      {line}
                    </p>
                  );
                })}
              </div>
            </div>
          )}
        </div>
      ) : (
        <div className="flex-1 flex flex-col items-center justify-center text-center p-8 text-slate-400">
          <BookOpen size={48} className="mb-4 text-slate-300" />
          <p className="text-lg font-medium text-slate-500">
            Select a topic to start learning
          </p>
          <p className="text-sm">
            Content is generated by Gemini AI for personalized explanations.
          </p>
        </div>
      )}
    </div>
  );
};

export default ContentViewer;
